import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useRouter } from 'next/router'
import { getCodeData } from '../src/lib/github'

// {codeData}: InferGetServerSidePropsType<typeof getServerSideProps>
const Home: NextPage = () => {

  const router = useRouter();

  useEffect(() => {
    getCodeData(router).then(code => {
      console.log(code)
    })
  }, [])

  return (
    <div className='bg-white h-screen w-full'>
      <Head>
        <title>Create Next App Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </div>
  )
}

// export const getServerSideProps: GetServerSideProps = async() => {

//   const config = {
//     headers: {
//       accept: 'application/json',
//     },
//     data: {},
//   };

//   const res = await fetch('https://raw.githubusercontent.com/nojuskybartas/cv/main/index.html')
//   const codeData = await res.text()
  
//   return {
//     props: {
//       codeData
//     }
//   }
// }

export default Home
